apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.4
  ports:
  - name: ftp
    port: 21
  - name: min
    port: 30020
  - name: max
    port: 30021
  selector:
    app: ftps
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: jelarose/ftps
        name: ftps
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 30020
          name: min
        - containerPort: 30021
          name: max
