apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.6
  ports:
  - name: http
    port: 80
  - name: ssl
    port: 443
  - name: ssh
    port: 22
  selector:
    app: nginx
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: jelarose/nginx
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: ssl
          containerPort: 443
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
